### PR TITLE
fix(private-registry): wrong English text

### PR DESCRIPTION
**Pull request by radireddy**
Below issues are fixed

1. Name was not shown in delete success message
2. Autofocus on input text in delete page
3. Few text translations are not proper in English and French

MBP-512

### CODE REVIEW

**Comment by radireddy** [comment]
@marie-j  below changes are done as part of this issue

1. Name was not shown in delete success message
2. Autofocus on input text in delete page
3. Few text translations are not proper in English and French

**Comment by jleveugle** [comment]
> @marie-j below changes are done as part of this issue
> 
> 1. Name was not shown in delete success message
> 2. Autofocus on input text in delete page
> 3. Few text translations are not proper in English and French

So, you should update your commit message ? :D

**Comment by radireddy** [comment]
yes I will do that

**Comment by jleveugle** [comment]
Don't forget to update your commit message :)

**Comment by radireddy** [comment]
I have changed the commit message

**Pull request merged**
