### PR TITLE
fix(pci.project.private.networks.vrack): update some translations

### PR DESCRIPTION
**Pull request by antleblanc**
# Update some translations

### :bug: Bug Fix

16646e9 - fix(pci.project.private.networks.vrack): update some translations

ref: MANAGER-2588

### CODE REVIEW

**Comment by marie-j** [comment]
This is not the content in the mockups. Also it will break consistency across all the pages with same CTAs

**Comment by antleblanc** [comment]
@marie-j Thanks for the feedback. I have update the pull request regarding the latest feedback that @fchabrolle gave me.

**Comment by fchabrolle** [comment]
we can have both, however in this specific case i think it's more correct, if it was just "créer un vRack" it was ok but the cta has more text than that

**Pull request merged**
