### PR TITLE
fix(emailpro): remove duplicate entry into translation

### PR DESCRIPTION
**Pull request by JeremyDec**
DTRUN-3581 / MANAGER-3443

### CODE REVIEW

**Comment by frenautvh** [comment]
if i'm not mistaken you cannot modify non french translations directly, you have to use the translator tool

**Comment by JeremyDec** [comment]
@frenautvh ok even for a mistaken value ? Not for a text modification ?

**Comment by frenautvh** [comment]
@JeremyDec i think your modifications will be overrided by the next translation "retrieve", you have fix the translation manually in the translator tool

**Comment by JeremyDec** [comment]
Ok, seen with @antleblanc, translation process launched in order to fix this issue. Closing PR

**Pull request closed without merging**
