### PR TITLE
New release

### PR DESCRIPTION
**Pull request by antleblanc**
# :package: New release

## :sparkles: Feature

MANAGER-3210 - feat(carrier.sip): init module
MANAGER-3210 - feat(carrier.sip): init application
MANAGER-3210 - feat(telephony.carrier.sip): add new module

### Other features

88bc8ac - feat(support): import translations

## :bug: Bug Fix

MANAGER-3471 - fix(cloud): fix edit icon size (#1449)
MANAGER-3486 - fix(enterprise-cloud-database): cleanup and mock data removal (#1434)
MANAGER-3497 - fix(hosting.website-coach): update order funnel redirection (#1440)
MANAGER-3693 - fix(web.hosting/webcoach): avoid displaying description twice (#1444)
MANAGER-3694 - fix(pci.stream): add name attribute on checkbox (#1441)

## :arrow_up: Upgrade

ab95f67 - build(deps): upgrade ng-ovh-otrs to v7.1.11
af288f3 - build(deps): upgrade ng-ovh-otrs to v7.1.11

## :heavy_check_mark: Test

5a73ab9 - test(stylelint): remove extra stylelint configuration files (#1446)

## :construction_worker_man: Build

975d810 - build(webpack): export region now can be passed to the server (#1453)

## :memo: Documentation

88c69da - docs: refers to the root CONTRIBUTING.md file (#1460)
644dacd - docs(readme): refers to the right package manage-webpack-config (#1461)
e1acf1c - docs(readme): refers to the right package manage-webpack-dev-server (#1461)

### @ovh-ux/component-rollup-config

3297580 - refactor(plugins.translations.utils): remove deprecated languages (#1452)

### CODE REVIEW

**Comment by ovh-cds** [comment]
CDS Report translations-checker#1808.0 ✘  
* Stage 1
  * Check ✘

**Comment by antleblanc** [comment]
CDS Report translations-checker is now fixed.

**Comment by ovh-cds** [comment]
CDS Report installation#5946.0 ■   
* Stage 1
  * Install ■

**Comment by ovh-cds** [comment]
CDS Report deploy_uxci_eu#5949.1 ✘  
* deploy_uxci
  * deploy_uxci ✘

**Comment by ovh-cds** [comment]
CDS Report build-monorepository#5958.0 ■   
* 
  * Build ■

**Comment by ovh-cds** [comment]
CDS Report deploy_uxci_ca#5959.1 ✘  
* deploy_uxci
  * deploy_uxci ✘

**Pull request merged**
