### PR TITLE
fix(pci.projects.new): pay credit with hipay after adding new method

### PR DESCRIPTION
**Pull request by Jisay**
# Pay credit with HiPay after adding new method

### :bug: Bug Fix

7f34ea7 - fix(pci.projects.new): pay credit with hipay after adding new method
c9ff8f3 - fix: avoid error when returning from hipay after credit pay

### CODE REVIEW

**Comment by ovh-cds** [comment]
CDS Report vrack#2596.1 ■   
* Stage 1
  * Build CA ✔ 
  * Build EU ■   
  * Build US ✔

**Comment by ovh-cds** [comment]
CDS Report pci#2596.1 ■   
* Stage 1
  * Build CA ✔ 
  * Build EU ✔ 
  * Build US ■

**Comment by ovh-cds** [comment]
CDS Report sms#2596.1 ■   
* Stage 1
  * Build CA ■   
  * Build EU ✔ 
  * Build US ■

**Comment by ovh-cds** [comment]
CDS Report public-cloud#2596.1 ■   
* Stage 1
  * Build CA ■   
  * Build EU ■   
  * Build US ■

**Comment by ovh-cds** [comment]
CDS Report telecom-task#2596.1 ■   
* Stage 1
  * Build CA ✔ 
  * Build EU ■   
  * Build US ■

**Comment by antleblanc** [comment]
@Jisay Could you please provide internal ticket reference in comment?

Thanks!

**Pull request closed without merging**
