### PR TITLE
Fix/ca build private registry

### PR DESCRIPTION
**Pull request by varun257**
## Remove private registry for CA region

resolves MANAGER-3018

### CODE REVIEW

**Comment by varun257** [comment]
@antleblanc can this go as hotfix ?

**Comment by antleblanc** [comment]
@varun257 For sure.

/cc @lizardK @jleveugle @cbourgois @marie-j

**Comment by marie-j** [comment]
@varun257 Could you please rebase on `master`? Thanks

**Comment by jleveugle** [comment]
Do you test the `US` build ? We should check if the menu (orchestration) appears empty or if we remove it because it is empty :)

**Pull request merged**
