### PR TITLE
fix(telephony.phone): fix order of function keys

### PR DESCRIPTION
**Pull request by JeremyDec**
ref : MANAGER-3242

resolves https://github.com/ovh-ux/ovh-manager-telecom/pull/1510.

### CODE REVIEW

**Comment by ovh-cds** [comment]
CDS Report freefax#4977.0 ✘  
* 
  * Build CA ✘  
  * Build EU ✘  
  * Build US ✘

**Comment by ovh-cds** [comment]
CDS Report telecom-task#4977.0 ✘  
* 
  * Build CA ✘  
  * Build EU ✘  
  * Build US ✘

**Comment by ovh-cds** [comment]
CDS Report pci#4977.0 ✘  
* 
  * Build CA ✘  
  * Build EU ✘  
  * Build US ✘

**Comment by ovh-cds** [comment]
CDS Report telecom-task#4977.1 ✘  
* 
  * Build CA ✘  
  * Build EU ✘  
  * Build US ✘

**Comment by ovh-cds** [comment]
CDS Report telecom-dashboard#4977.1 ✘  
* 
  * Build CA ✘  
  * Build EU ✘  
  * Build US ✘

**Comment by ovh-cds** [comment]
CDS Report vrack#4977.1 ✘  
* 
  * Build CA ✘  
  * Build EU ✘  
  * Build US ✘

**Comment by antleblanc** [comment]
Hello @JeremyDec!

I think it would be great to precise a [`Co-authored-by:`](https://help.github.com/en/articles/creating-a-commit-with-multiple-authors) in order to give credit
to the contributor.

Do you think it could be possible to amend your commit?

Thanks!

ref: https://github.com/ovh-ux/ovh-manager-telecom/commit/cbb1a7a1e889dde9e0c1d0eaf470a639f2069383.patch

**Comment by JeremyDec** [comment]
Hello @antleblanc, the PR is backported into the legacy repository, the co-author will be added then into that one.

Closing the PR

**Pull request closed without merging**
