### PR TITLE
refactor(navbar): remove non translated english locales

### PR DESCRIPTION
**Pull request by Jisay**

### CODE REVIEW

**Comment by Jisay** [comment]
Yes it makes sense to remove it. But it should also be good to have that config at only one place?

**Comment by antleblanc** [comment]
@Jisay Is there any internal ticket reference related to that change?

**Comment by marie-j** [comment]
> Yes it makes sense to remove it. But it should also be good to have that config at only one place?

@Jisay I agree, we should have this list at one place and reuse it everywhere its needed

**Comment by Jisay** [comment]
> > Yes it makes sense to remove it. But it should also be good to have that config at only one place?
> 
> @Jisay I agree, we should have this list at one place and reuse it everywhere its needed

@marie-j I have centralized the available languages in ```@ovh-ux/manager-core``` as ```@ovh-ux/manager-navbar``` has this module as peerDependency.

**Pull request merged**
